myApp/myApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
]

myApp/polls/urls.py
from django.urls import path
from . import views


app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/hasil/', views.HasilView.as_view(), name='hasil'),
    path('<int:pertanyaan_id>/suara/', views.suara, name='suara'),
    
]

myApp/polls/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.

class Pertanyaan(models.Model):
    pertanyaan_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.pertanyaan_text
    
    def was_publish_terbaru(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    

class Pilih(models.Model):
    pertanyaan= models.ForeignKey(Pertanyaan, on_delete=models.CASCADE)
    pilih_text = models.CharField(max_length=200)
    suara = models.IntegerField(default=0)

    def __str__(self):
        return self.pilih_text
    
    

myApp/polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Pilih, Pertanyaan
# Create your views here.

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'pertanyaan_terakhir_list'

    def get_queryset(self):
        return Pertanyaan.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Pertanyaan
    template_name = 'polls/detail.html'
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Pertanyaan.objects.filter(pub_date__lte=timezone.now())


class HasilView(generic.DetailView):
    model = Pertanyaan
    template_name='polls/hasil.html'

def suara(request, pertanyaan_id):
    pertanyaan = get_object_or_404(Pertanyaan, pk=pertanyaan_id)
    try:
        selected_pilih = pertanyaan.pilih_set.get(pk=request.POST['pilih'])
    except (KeyError, Pilih.DoesNotExist):
        return render(request, 'polls/detail.html',{
            'pertanyaan': pertanyaan,
            'error_message': "Kamu tidak memilih pilihan",
        })
    else:
        selected_pilih.suara += 1
        selected_pilih.save()
        return HttpResponseRedirect(reverse('polls:hasil', args=(pertanyaan.id)))

    

myApp/polls/templates/polls/detail.html
<form action="{% url 'polls:suara' pertanyaan.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ pertanyaan.pertanyaan_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for pilih in pertanyaan.pilih_set.all %}
            <input type="radio" name="pilih" id="pilih{{ forloop.counter }}" value="{{ pilih.id }}">
            <label for="pilih{{ forloop.counter }}">{{ pilih.pilih_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
    </form>

myApp/polls/templates/polls/hasil.html
<h1>{{ pertanyaan.pertanyaan_text }}</h1>

<ul>
{% for pilih in pertanyaan.pilih_set.all %}
    <li>{{ pilih.pilih_text }} -- {{ pilih.suara }} vote{{ pilih.suara|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' pertanyaan.id %}">Vote again?</a>

myApp/polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" href="{% static 'polls/style.css' %}">

    
{% if pertanyaan_terakhir_list %}
    <ul>
    {% for question in pertanyaan_terakhir_list %}
    <li><a href="{% url 'polls:detail' question.id %}">{{ question.pertanyaan_text }}</a></li>
        
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>

{% endif %}

{% block branding %}
<h1 id="site-name"><a href="{% url 'admin:index' %}">Polls Administration</a></h1>
{% endblock %}